### ISSUE TITLE
Add supprort for Rooms

### ISSUE THREAD

**Issue by Sikora00** [Sikora00/sdj-api#17]

**Comment by MaciejSikorski** [comment]
Room needs to have default radio url

**Comment by wjanaszek** [comment]
Room entity:
- id (UUID)
- name (string)

**Comment by Sikora00** [comment]
Ok, to na pewno trzeba stworzyć encję Room, z id (przydało by się ogarnąć jaki format mają id channelu, na slacku, albo w ogóle nazwać to channel), może być name, tak jak wyżej, powinniśmy móc ustawić default stream, żeby np na kanale rock ustawić defaultowo open.fm/rock i relacje do vote i do queued track

**Comment by Sikora00** [comment]
Potem zaczną się schody, trzeba będzie zrobić żeby playlist service zwracał odpowiednią następną piosenkę, zależnie jaki channel o nią zawołał

**Comment by Sikora00** [comment]
i trzeba będzie porobić też namespacy, czy jak to się nazywa na komunikacji ices <-> redis <-> backend
Na razie można zahardcodować jaki kolwiek, byle później, można było to połączyć z taskiem #19 i tylko wstawić w odpowiednie miejsca channelId

**Comment by wjanaszek** [comment]
Jaka relacja do vote, a jaka do queued track? 

channel -< vote
channel -< queued track

**Comment by Sikora00** [comment]
kolumna channelId powinna się znaleźć w vote i queued track czyli channel może mieć wiele vote i queued track a one mogą być w jednym channelu

**Comment by wjanaszek** [comment]
Zrobiłem PR, żebyś mógł przejrzeć czy idzie to w dobrym kierunku :P Nie ma jeszcze obsługi channelId ze slacka, muszę poczytać jaki ma format itp.
